// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Category struct {
	ID       uuid.UUID     `json:"id"`
	Name     string        `json:"name"`
	Slug     string        `json:"slug"`
	ParentID uuid.NullUUID `json:"parent_id"`
}

type InstagramLink struct {
	ID        uuid.UUID    `json:"id"`
	ProductID uuid.UUID    `json:"product_id"`
	PostUrl   string       `json:"post_url"`
	EmbedHtml string       `json:"embed_html"`
	CachedAt  sql.NullTime `json:"cached_at"`
}

type Inventory struct {
	VariantID uuid.UUID `json:"variant_id"`
	Quantity  int32     `json:"quantity"`
	Reserved  int32     `json:"reserved"`
}

type Order struct {
	ID              uuid.UUID      `json:"id"`
	UserID          uuid.NullUUID  `json:"user_id"`
	Status          string         `json:"status"`
	TotalCents      int32          `json:"total_cents"`
	StripeSessionID sql.NullString `json:"stripe_session_id"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type OrderItem struct {
	ID         uuid.UUID `json:"id"`
	OrderID    uuid.UUID `json:"order_id"`
	VariantID  uuid.UUID `json:"variant_id"`
	Quantity   int32     `json:"quantity"`
	PriceCents int32     `json:"price_cents"`
}

type Product struct {
	ID               uuid.UUID     `json:"id"`
	Title            string        `json:"title"`
	Description      string        `json:"description"`
	CategoryID       uuid.NullUUID `json:"category_id"`
	Brand            string        `json:"brand"`
	Condition        string        `json:"condition"`
	PriceCents       int32         `json:"price_cents"`
	SellerID         uuid.NullUUID `json:"seller_id"`
	InstagramPostUrl string        `json:"instagram_post_url"`
	CreatedAt        time.Time     `json:"created_at"`
	UpdatedAt        time.Time     `json:"updated_at"`
}

type ProductImage struct {
	ID        uuid.UUID `json:"id"`
	ProductID uuid.UUID `json:"product_id"`
	R2Key     string    `json:"r2_key"`
	Url       string    `json:"url"`
	Position  int32     `json:"position"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
	CreatedAt    time.Time `json:"created_at"`
}

type Variant struct {
	ID        uuid.UUID      `json:"id"`
	ProductID uuid.UUID      `json:"product_id"`
	Size      string         `json:"size"`
	Color     string         `json:"color"`
	Sku       sql.NullString `json:"sku"`
	CreatedAt time.Time      `json:"created_at"`
}
