// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (title, description, category_id, brand, condition, price_cents, instagram_post_url)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, title, description, category_id, brand, condition, price_cents, seller_id, instagram_post_url, created_at, updated_at
`

type CreateProductParams struct {
	Title            string        `json:"title"`
	Description      string        `json:"description"`
	CategoryID       uuid.NullUUID `json:"category_id"`
	Brand            string        `json:"brand"`
	Condition        string        `json:"condition"`
	PriceCents       int32         `json:"price_cents"`
	InstagramPostUrl string        `json:"instagram_post_url"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.Title,
		arg.Description,
		arg.CategoryID,
		arg.Brand,
		arg.Condition,
		arg.PriceCents,
		arg.InstagramPostUrl,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CategoryID,
		&i.Brand,
		&i.Condition,
		&i.PriceCents,
		&i.SellerID,
		&i.InstagramPostUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, id)
	return err
}

const getProduct = `-- name: GetProduct :one
SELECT id, title, description, category_id, brand, condition,
       price_cents, seller_id, instagram_post_url, created_at, updated_at
FROM products
WHERE id = $1
`

func (q *Queries) GetProduct(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CategoryID,
		&i.Brand,
		&i.Condition,
		&i.PriceCents,
		&i.SellerID,
		&i.InstagramPostUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, title, description, category_id, brand, condition,
       price_cents, seller_id, instagram_post_url, created_at, updated_at
FROM products
ORDER BY created_at DESC
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CategoryID,
			&i.Brand,
			&i.Condition,
			&i.PriceCents,
			&i.SellerID,
			&i.InstagramPostUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
